### ISSUE TITLE
jsonschema validation error when creating topic

### ISSUE THREAD

**Issue by Elderx** [kangasta/fdbk_ruuvi_reporter#5]
Trying to run: fdbk-ruuvi-reporter --create-topic test XX:XX:XX:XX:XX:XX --db-connection fdbk_dynamodb_plugin
and getting this error.

Traceback (most recent call last):
  File "/usr/local/bin/fdbk-ruuvi-reporter", line 15, in <module>
    create_topic(args.db_connection, args.db_parameters, *args.create_topic)
  File "/usr/local/lib/python3.7/dist-packages/fdbk_ruuvi_reporter/main.py", line 44, in create_topic
    topic_id = connection.add_topic(**create_topic_dict(mac, name))
  File "/usr/local/lib/python3.7/dist-packages/fdbk_dynamodb_plugin/_dynamodb_connection.py", line 34, in add_topic
    topic_d = generate_topic_dict(name, add_id=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/fdbk/utils/_format.py", line 143, in generate_topic_dict
    validate_topic_dict(topic_d)
  File "/usr/local/lib/python3.7/dist-packages/fdbk/validate.py", line 24, in validate_topic_dict
    _validate_dict(topic_d, 'topic-in')
  File "/usr/local/lib/python3.7/dist-packages/fdbk/validate.py", line 18, in _validate_dict
    validate(instance=input_dict, schema=schema)
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'ruuvitag' is not one of ['topic', 'template']

Failed validating 'enum' in schema['properties']['type']:
    {'enum': ['topic', 'template']}

On instance['type']:
    'ruuvitag'

Also tried to run: fdbk-ruuvi-reporter --create-topic ${test} ${XX:XX:XX:XX:XX:XX} --db-connection fdbk_dynamodb_plugin
but then the error was: fdbk-ruuvi-reporter: error: argument --create-topic: expected 2 arguments.

So, how is the creation of the topic suppose to happen `

**Comment by kangasta** [comment]
Hi, thanks for the feedback. You have the command right. I pushed a new version of `fdbk` yesterday, which is not backwards compatible, but matches the current `install_requires` line.

**Comment by Elderx** [comment]
Confirmed working after pulling update, thanks.
